### ISSUE TITLE
scoop bucket does not seem to be functioning

### ISSUE THREAD

**Issue by PizzaKirby** [charmbracelet/scoop-bucket#1]
It seems like this not a functioning scoop bucket.
Adding it via `scoop bucket add charm https://github.com/charmbracelet/scoop-bucket.git` results in 
```
❯ scoop bucket add charm https://github.com/charmbracelet/scoop-bucket.git
Checking repo... OK
The charm bucket was added successfully.
~
❯ scoop bucket list

Name   Source                                            Updated             Manifests
----   ------                                            -------             ---------
charm  https://github.com/charmbracelet/scoop-bucket.git 17/05/2023 21:08:46         0
extras https://github.com/ScoopInstaller/Extras          20/05/2023 10:24:59      1866
main   https://github.com/ScoopInstaller/Main.git        20/05/2023 10:25:51      1197
```
The official [bucket template](https://github.com/ScoopInstaller/BucketTemplate) and the [code]([scoop/buckets.ps1](https://github.com/ScoopInstaller/Scoop/blob/master/lib/buckets.ps1#L24)) used to fetch the directory containing the manifests require that a `$root/bucket` directory is present containing the manifests.

This should be a relatively easy fix by moving the manifests to a `$root/bucket` directory, I've tested it locally and it seems to work fine.

**Comment by caarlos0** [comment]
this was fixed a long while ago, forgot to close it here.

Thanks for the report @PizzaKirby
