### ISSUE TITLE
shorten commit messages

### ISSUE THREAD

**Issue by dezren39** [charmbracelet/scoop-bucket#3]
hi so these messages show up directly in the cli,

i suggest that you use a very terse format so that it's cleaner to read.

instead of
```
Scoop update for <appName> version <version>
```
the convention apparently common in scoop repos is
```
<appName>: Update to version <version>
```
but personally i'm even partial to shorten that further
```
<appName>: <version>
```
or
```
<appName>: <version> (was: <oldVersion>)
```
or something.

the common convention is probably best.

either way i suggest that you get rid of any prefix before appName.

even just delete "Scoop update for " and leave it at that?

like obviously it's a scoop update you are in the scoop bucket etc.

scoop does follow standard header/summary conventions so you could include additional info below the fold if you really wanted to be sure that people knew it was an autoupdate.
```
<appName>: Update to version <version>

autoupdate on <date>
autoupdate job <url>
```
is this in your 'meta' repo somewhere i guess?

**Comment by caarlos0** [comment]
these messages are auto-generated by goreleaser, no good reason to change them, so we'll keep as is for now.
